version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: fastapi
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/fastapi
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:80"
    volumes:
      - .:/app

volumes:
  mysql_data:
